Pull before commiting
```
[master 2e497c2] Update generated files
 2 files changed, 33 insertions(+), 51 deletions(-)
To https://github.com/yooksi/github-stats
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/yooksi/github-stats'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```